---
- name: install unzip
  pacman:
    name: unzip
    update_cache: yes

- name: install ca-certificates
  pacman:
    name: ca-certificates

- name: install python
  pacman:
    name: python

- name: install python-requests
  pacman:
    name: python-requests

